### PR TITLE
fix: consider all oracles expirations

### PR DESCRIPTION
**Pull request by jyeshe**
refs #1278

### CODE REVIEW

**Review by sborrazas — COMMENTED** [review]
Should this change include a migration?

**Comment by jyeshe** [comment]
> Should this change include a migration? 
Reindexation will be required to consider the ` old_oracles_registered`.

**Comment by sborrazas** [comment]
> > Should this change include a migration?
> 
> Reindexation will be required to consider the `old_oracles_registered`.

I would imagine there are not that many oracle registrations/expirations, perhaps we can iterate through registrations/expirations and build a count for each generation and then update the total/delta? Similar to how it was done here for example: https://github.com/aeternity/ae_mdw/commit/d965275c5173e8406ceb6f546bb054a38f30df2d#diff-6bec92ed38dd3e93f9c2600420a2eca3d0b410d013b67b4621c61cfbfca967f1

**Comment by jyeshe** [comment]
> > > Should this change include a migration?
> > 
> > 
> > Reindexation will be required to consider the `old_oracles_registered`.
> 
> I would imagine there are not that many oracle registrations/expirations, perhaps we can iterate through registrations/expirations and build a count for each generation and then update the total/delta? Similar to how it was done here for example: [d965275#diff-6bec92ed38dd3e93f9c2600420a2eca3d0b410d013b67b4621c61cfbfca967f1](https://github.com/aeternity/ae_mdw/commit/d965275c5173e8406ceb6f546bb054a38f30df2d#diff-6bec92ed38dd3e93f9c2600420a2eca3d0b410d013b67b4621c61cfbfca967f1)

The issue is that we need to simulate the registrations, registrations of only new oracles and expirations (some are registered and expires multiple times).

**Pull request merged**
