### PR TITLE
feat: add txs per second stat on /stats

### PR DESCRIPTION
**Pull request by sborrazas**
TPS is calculated by grabbing the microblocks from a single gen and using the total transactions from that gen

refs #821

### CODE REVIEW

**Comment by thepiwo** [comment]
are you sure this returns reliable numbers, the key block times are not exact as discussed in chat

**Comment by sborrazas** [comment]
@thepiwo none of these numbers are going to be reliable, so it's just an approximation. What I did was grab all of the microblocks timeframe and transactions and do `(total_txs / total_microblocks_timeframe)` per key block. Right now that gives me a value of 4.86 txs/sec (height ~280k)

**Review by jyeshe — APPROVED** [review]
Not sure about the full scope of the requirement but if microblock duration have been uniform there might be a higher max tps per microblock that maybe could be added to the stat as well. Otherwise looks good to me.

**Comment by thepiwo** [comment]
@sborrazas whats the maximum tps you can find overall?

**Comment by sborrazas** [comment]
> @sborrazas whats the maximum tps you can find overall?

haven't yet reached the end of syncing, but I'm at 33.72txs/sec max

**Comment by thepiwo** [comment]
@sborrazas at height 7106 was a mainnet speed test and they measured 116tps

**Comment by sborrazas** [comment]
Currently the gen that has the most txs per sec is 7077, and so far no gen has done better:

```
GEN 7077 (https://mainnet.aeternity.io/mdw/v2/blocks?scope=gen:7077-7077)
total time = (1544618518728 - 1544618437340)
total txs = 3003
tps = 3003 / (1544618518728 - 1544618437340) * 1000 = 36.9

GEN 7106 (https://mainnet.aeternity.io/mdw/v2/blocks?scope=gen:7106-7106)
total time = (1544622380518 - 1544621891738)
total txs = 8648
tps = 8648 / (1544622380518 - 1544621891738) * 1000 = 17.69
```

**Comment by sborrazas** [comment]
Sorry, I take that back, best gen so far was 34057:
```
total time = (1549485892135 - 1549485890970)
total txs = 61
tps = 61 / (1549485892135 - 1549485890970) * 1000 = 52.36
```

**Review by thepiwo — APPROVED** [review]
lets have it like this, but we may have to adjust when someone proposes a better algorithm :D

**Pull request merged**
