### PR TITLE
feat: add last 24 hours transactions count

### PR DESCRIPTION
**Pull request by sborrazas**
refs #1593

### CODE REVIEW

**Review by jyeshe — APPROVED** [review]

**Comment by janmichek** [comment]
@sborrazas Could you clarify what is the URL for the endpoint, please? Does not seems to be exposed here

https://mainnet.aeternity.io/mdw/v2/deltastats?limit=10
https://mainnet.aeternity.io/mdw/v2/totalstats?limit=10
https://mainnet.aeternity.io/mdw/v3/statistics/transactions

**Comment by janmichek** [comment]
ping

**Comment by sborrazas** [comment]
@janmichek it's available here, https://mainnet.aeternity.io/mdw/v2/stats but I'm not seeing any yet. Looking into it

**Comment by janmichek** [comment]
Aha, thanks. I did not know as this endpoint is not documented here https://petstore.swagger.io/?url=https://mainnet.aeternity.io/mdw/v2/api

**Comment by janmichek** [comment]
Seems to work now

**Pull request merged**
