### PR TITLE
fix: adjust tuple structure sent on AEX9 balances endpoints

### PR DESCRIPTION
**Pull request by sborrazas**
This was found using dialyzer, and was causing the AEX9 balance endpoints to return a 500 error.

### CODE REVIEW

**Comment by sborrazas** [comment]
@thepiwo should I create a GH issue for this?

**Review by thepiwo — COMMENTED** [review]
looks good to me, will leave for others to review as well

**Comment by thepiwo** [comment]
@sborrazas we don't need an issue if we already have a fix

**Review by jyeshe — APPROVED** [review]
:+1:

**Review by Artur64 — APPROVED** [review]
Looks good to me, I will also add some tests to aex9 controller

**Pull request merged**
