### PR TITLE
feat: db transactions per microblock

### PR DESCRIPTION
**Pull request by jyeshe**
## What

Commits sync changes per micro block.

## Why

Mnesia transaction log is not being fully committed.
Contribute to #387
Contribute to #396 

## Additional notes

This paves the way to make instant syncs of AEX9 txs #211. Not sufficient but one step forward to the next step of having syncs per transaction.

### CODE REVIEW

**Review by thepiwo — APPROVED** [review]

**Review by thepiwo — COMMENTED** [review]
as discussed in standup we can't split transactions for now as our sync is key-block based not micro-block based, right?

**Comment by jyeshe** [comment]
> as discussed in standup we can't split transactions for now as our sync is key-block based not micro-block based, right?

Since the mdw uses a key-value DB most writes operations are idempotent from what I have looked but I will review it again and let it sync to see if there is no `:not_found` issue after it.

**Comment by jyeshe** [comment]
@thepiwo @sborrazas 
The PR is updated with the sync continuing from last microblock synced in case you wanna trigger a new test sync. 

Saving the keyblock at the end fixes the `/blocks/` (shows all microblocks of the generation).  

So from what it's tracked so far, there is only a pending change on async task that needs to be enqueued only after the microblock is commited.

I got only one error on multiple restarts that already existed (and will be fixed in the next commit):
```
{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"got empty list">>},[{'Elixir.AeMdw.Util','one!',1,[{file,"lib/ae_mdw/util.ex"},{line,5}]},{'Elixir.AeMdw.Db.Sync.Stat',store_mutation,1,[{file,"lib/ae_mdw/db/sync/stat.ex"},{line,17}]},{'Elixir.AeMdw.Db.Sync.Transaction',sync_generation,2,[{file,"lib/ae_mdw/db/sync/transaction.ex"},{line,162}]},{'Elixir.Enum',reduce_range_inc,4,[{file,"lib/enum.ex"},{line,3371}]},{'Elixir.AeMdw.Db.Sync.Transaction',sync,3,[{file,"lib/ae_mdw/db/sync/transaction.ex"},{line,57}]},{'Elixir.AeMdw.Db.Sync',run_action,1,[{file,"lib/ae_mdw/db/sync/sync.ex"},{line,99}]}]}
```

**Comment by thepiwo** [comment]
what happens in case of micro-forks? e.g. Miner A produces a keyblock then follows with mb1 -> mb2 -> mb3 then Miner B produces a keyblock but only picks up the microblocks from mb2 and reprocesses the txs from mb3 in his new micro block?

**Comment by jyeshe** [comment]
> what happens in case of micro-forks? e.g. Miner A produces a keyblock then follows with mb1 -> mb2 -> mb3 then Miner B produces a keyblock but only picks up the microblocks from mb2 and reprocesses the txs from mb3 in his new micro block?

This is the point I have just commented in the meeting:
https://github.com/aeternity/ae_mdw/blob/ca7f295d9de201c4dd45cdb03dfcddce86b39e21/lib/ae_mdw/db/sync/sync.ex#L33-L35

If there is a running sync process it does not run the fork concurrently and waits for the process with multiple microblocks commit to finish.

When the sync process finishes, then the fork runs here:
https://github.com/aeternity/ae_mdw/blob/ca7f295d9de201c4dd45cdb03dfcddce86b39e21/lib/ae_mdw/db/sync/sync.ex#L44-L45

**Comment by jyeshe** [comment]
WIP: Stats needs a cache reload in case the `last_mbi` is not -1

**Comment by jyeshe** [comment]
Depends on #403

**Comment by jyeshe** [comment]
@thepiwo @sborrazas now with #403 this PR is ready for review and full sync test.
Sum stat reading might still happen if mdw is stopped (not always but stopping and starting multiple times reproduces it).
Investigation and enhancement issue reported [here](https://github.com/aeternity/ae_mdw/issues/404)

**Comment by thepiwo** [comment]
> what happens in case of micro-forks? e.g. Miner A produces a keyblock then follows with mb1 -> mb2 -> mb3 then Miner B produces a keyblock but only picks up the microblocks from mb2 and reprocesses the txs from mb3 in his new micro block?

I still don't understand how that is handled here, what concretely happens to the info and txs that were eventually processed already from mb3 in this example?

**Comment by jyeshe** [comment]
> > what happens in case of micro-forks? e.g. Miner A produces a keyblock then follows with mb1 -> mb2 -> mb3 then Miner B produces a keyblock but only picks up the microblocks from mb2 and reprocesses the txs from mb3 in his new micro block?
> 
> I still don't understand how that is handled here, what concretely happens to the info and txs that were eventually processed already from mb3 in this example?

It means that the sequence of sync and fork invalidation and the fork process itself are kept unchanged. The fork will execute at the same moment as it would before this change.
The only difference will be that instead of the sync process have a big mnesia transaction it will have multiple smaller ones.

**Comment by thepiwo** [comment]
@jyeshe so we are not processing micro-blocks once received, still just when the key-block is final?

**Comment by jyeshe** [comment]
> @jyeshe so we are not processing micro-blocks once received, still just when the key-block is final?

@thepiwo good question, exactly. 

The full sequence is (change only in the 5th step):
1. mdw is notified that there is something to be synced
2. mdw calls the node to get the top height and spawns a process to sync until this top height less 200 generations.
3. for each height until the last to be synced, it loads the key block and all microblocks walking from the last to the first microblock.
4. reverses the list of microblocks and syncs the generation (the key block and all microblocks).
5. while syncing a generation, the mdw commits the txs for each microblock (instead of committing all txs of the generation at once).

**Comment by jyeshe** [comment]
> > @jyeshe so we are not processing micro-blocks once received, still just when the key-block is final?
> 
> @thepiwo good question, exactly.
> 
> The full sequence is (the scope of the PR is in the 5th step):
> 
>     1. mdw is notified that there is something to be synced
> 
>     2. mdw calls the node to get the top height and spawns a process to sync until this top height less 200 generations.
> 
>     3. for each height until the last to be synced, it loads the key block and all microblocks walking from the last to the first microblock.
> 
>     4. reverses the list of microblocks and syncs the generation (the key block and all microblocks).
> 
>     5. while syncing a generation, the mdw commits the txs for each microblock (instead of committing all txs of the generation at once).

PS: 
The top height - 200 is used only when the Mdw starts (`:safe` param):
https://github.com/aeternity/ae_mdw/blob/27d7fbe509ad219460aab13ee26c0c6c5f3274fb/lib/ae_mdw/db/sync/sync.ex#L31 

On the next chain notifications to the subscriber, it gets the top height - 1:
https://github.com/aeternity/ae_mdw/blob/27d7fbe509ad219460aab13ee26c0c6c5f3274fb/lib/ae_mdw/db/sync/sync.ex#L85

**Comment by jyeshe** [comment]
@thepiwo a complement:
The top height - 200 is used only when the Mdw starts (`:safe` param):
https://github.com/aeternity/ae_mdw/blob/27d7fbe509ad219460aab13ee26c0c6c5f3274fb/lib/ae_mdw/db/sync/sync.ex#L31 

On the next chain notifications to the subscriber, it gets the top height - 1:
https://github.com/aeternity/ae_mdw/blob/27d7fbe509ad219460aab13ee26c0c6c5f3274fb/lib/ae_mdw/db/sync/sync.ex#L85

**Comment by thepiwo** [comment]
I understand, makes sense I think

**Review by thepiwo — APPROVED** [review]

**Comment by jyeshe** [comment]
rebased for 387-mb-commit-with-stat-fix

**Comment by jyeshe** [comment]
@thepiwo @sborrazas the Model.Block `tx_index` was saved previously after a range of generations. Now it's saved after each generation. With this, the mdw knows if the generation was fully synced. 

The other change was to resync in idempotent manner the generation of the last tx synced (last microblock synced).

**Review by sborrazas — APPROVED** [review]
LGTM

**Pull request merged**
