### PR TITLE
chore: remove phoenix_swagger

### PR DESCRIPTION
**Pull request by jyeshe**
## What

- Removes phoenix_swagger lib

## Why

- Latest riverside requires poison 5.0 and phoenix_swagger up to 3.0.
- phoenix_swagger is not used anymore to generate swagger files, only to render the Swagger UI

### CODE REVIEW

**Comment by jyeshe** [comment]
@thepiwo @sborrazas a PR for the phoenix_swagger was submitted. If preferred for some reason to avoid the static assets there is also this option:
https://github.com/aeternity/ae_mdw/blob/e81a2b622028b4311537400b722576237dba4a64/mix.exs#L143 (to be removed if  the static assets are merged)

**Comment by jyeshe** [comment]
Drafting to solve existing issue of: https://mainnet.aeternity.io/mdw/swagger

**Comment by jyeshe** [comment]
> Drafting to solve existing issue of: https://mainnet.aeternity.io/mdw/swagger

Prefixed the `/mdw` when not present on the forwarding path (currently applies to dev, test and prod and after reorganizing the prod we might remove from dev and test).

**Review by thepiwo — COMMENTED** [review]
do we really need to serve the swagger UI? as long as we expose the definitions any hosted UI can be used right? Maybe we can include an example for that in the docs

**Comment by jyeshe** [comment]
> do we really need to serve the swagger UI? as long as we expose the definitions any hosted UI can be used right? Maybe we can include an example for that in the docs

Done (cc @sborrazas)

**Review by thepiwo — APPROVED** [review]

**Review by sborrazas — APPROVED** [review]

**Pull request merged**
