### PR TITLE
test: add local js SDK setup for testing purposes

### PR DESCRIPTION
**Pull request by sborrazas**

### CODE REVIEW

**Review by thepiwo — COMMENTED** [review]
if the goal is to just use it locally lets put it in a separate repo, if we need such thing for unit tests I think we should look for other possibilities, e.g. trying to use the node directly or using the elixir sdk (if still works)

**Comment by sborrazas** [comment]
@thepiwo indeed the Elixir SDK would be ideal. Perhaps we could create a task to check if it works and integrate it for local testing?

**Comment by thepiwo** [comment]
@sborrazas feel free to take a few hours to try it out

**Comment by marc0olo** [comment]
> @sborrazas feel free to take a few hours to try it out

yeah, maybe we could even discuss to make it Iris compatible and feature complete. I would support this

**Review by jyeshe — APPROVED** [review]
Looks good for the JS SDK (in case we won't use the Elixir SDK).

**Comment by thepiwo** [comment]
I would propose to close this, do you have different opinions?

**Comment by sborrazas** [comment]
Closing, perhaps next sprint we can start looking into bringing the Elixir SDK back to life.

**Pull request closed without merging**
