### PR TITLE
feat: add aex9 presence after event

### PR DESCRIPTION
**Pull request by jyeshe**
## What

- Replaces the dry run with events in regards to sync (next is the endpoint)
- Improves test setup

## Why

Refs #969
Scoped as part of the latest request to replace the aex9 dry-run balance with the event ones.

### CODE REVIEW

**Review by thepiwo — APPROVED** [review]
thats something we overlooked in earlier refactorings?

**Comment by jyeshe** [comment]
> thats something we overlooked in earlier refactorings?

it's part of the task of converting the aex9 endpoints to use the events instead of the dry-running

**Comment by thepiwo** [comment]
@jyeshe is there anything else left to call it "complete"?

**Comment by thepiwo** [comment]
@jyeshe thanks for the clarification

**Review by sborrazas — APPROVED** [review]

**Pull request merged**
