### PR TITLE
refactor: add oracle expiration mutation when syncing

### PR DESCRIPTION
**Pull request by sborrazas**

### CODE REVIEW

**Review by thepiwo — APPROVED** [review]
lgtm

**Review by jyeshe — CHANGES_REQUESTED** [review]
Until the persistence issue is solved, I would rather keep the validations in the transitions in oracle state.

**Comment by sborrazas** [comment]
@jyeshe definitely, we shouldn't merge this PR until those other issues are resolved

**Comment by jyeshe** [comment]
> @jyeshe definitely, we shouldn't merge this PR until those other issues are resolved

@sborrazas 
Or add the validations and merge these PRs as they provide an important change of making the transactions lighter (with heavy reading before the transaction).

**Review by jyeshe — APPROVED** [review]

**Comment by thepiwo** [comment]
@jyeshe @sborrazas is there any remaining blocker to merge this?

**Pull request merged**
