### PR TITLE
fix: index the origin of contracts created via Chain.clone/create

### PR DESCRIPTION
**Pull request by sborrazas**
refs #425

### CODE REVIEW

**Review by thepiwo — APPROVED** [review]

**Review by jyeshe — COMMENTED** [review]
Code looks good and all tests passed except this one that looks like could be deleted:
1) test logs when contract log doesn't have a creation txi, contract_id shouldn't be nil (Integration.AeMdwWeb.ContractControllerTest)
     test/integration/ae_mdw_web/controllers/contract_controller_test.exs:180
     ** (RuntimeError) expected response with status 200, got: 400, with body:
     "{\"error\":\"invalid id: ct_eJhrbPPS4V97VLKEVbSCJFpdA4uyXiZujQyLqMFoYV88TzDe6\"}"

In this PR or following one after the release we could delete the Model.Origin table.

**Comment by sborrazas** [comment]
@jyeshe that test doesn't fail for me, and it looks like what it's testing is correct (special hard-coded contracts have negative values for the creation txi). But perhaps we should probably just store the negative value, and not display it to the user, display "nil" instead. Thoughts?

**Comment by jyeshe** [comment]
> @jyeshe that test doesn't fail for me, and it looks like what it's testing is correct (special hard-coded contracts have negative values for the creation txi). But perhaps we should probably just store the negative value, and not display it to the user, display "nil" instead. Thoughts?

The tests only had run with the `1.5.0-07cf3e4` database skipping two migrations. With the #481 and rerunning the migrations the test passed. Better to keep the test as you're saying because of the contracts from the fork.

**Comment by jyeshe** [comment]
Gonna do a final validation after the #481 merge (or similar fix).

**Comment by jyeshe** [comment]
```
test events_mutations/4 creates name update mutation (Integration.AeMdw.Db.Sync.ContractTest)
     test/integration/ae_mdw/db/sync/contract_test.exs:45
test events_mutations/4 creates name transfer mutation (Integration.AeMdw.Db.Sync.ContractTest)
     test/integration/ae_mdw/db/sync/contract_test.exs:16
```
After the merge of #481 and changing the `Sync.Contract.events_mutations` calls on the tests above, I think we are good to go and have all contracts indexed :pray:

**Review by jyeshe — APPROVED** [review]
tests passed

**Pull request merged**
