### PR TITLE
feat: add v2 oracles endpoints

### PR DESCRIPTION
**Pull request by sborrazas**
refs #498

### CODE REVIEW

**Review by thepiwo — APPROVED** [review]

**Review by jyeshe — CHANGES_REQUESTED** [review]
The errors listed in #541 were reduced to:

```
1) test inactive_oracles get inactive oracles with default direction=backward and default limit (Integration.AeMdwWeb.OracleControllerTest)
     test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:198
     match (=) failed
     code:  assert @default_limit = length(next_oracles)
     left:  @default_limit
     right: 8
     stacktrace:
       test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:217: (test)

....

  2) test oracle it returns oracles registered through contract calls using Oracle.register (Integration.AeMdwWeb.OracleControllerTest)
     test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:49
     ** (RuntimeError) expected response with status 200, got: 404, with body:
     "{\"error\":\"not found: ok_zi3UaZkNWhxfR57tEE7ymNyQ2qHqtdZjQGQ7VpnmQ7MFdSL8A\"}"
     code: conn |> get("/oracle/#{oracle_id}") |> json_response(200)
     stacktrace:
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:369: Phoenix.ConnTest.response/2
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:415: Phoenix.ConnTest.json_response/2
       test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:68: (test)

..........

  3) test inactive_oracles it gets inactive oracles with default direction=backward and default limit (Integration.AeMdwWeb.OracleControllerTest)
     test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:387
     match (=) failed
     code:  assert @default_limit = length(next_oracles)
     left:  @default_limit
     right: 2
     stacktrace:
       test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:408: (test)

.

  4) test oracles get all oracles with default direction=backward and default limit (Integration.AeMdwWeb.OracleControllerTest)
     test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:73
     match (=) failed
     code:  assert @default_limit = length(next_oracles)
     left:  @default_limit
     right: 2
     stacktrace:
       test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:91: (test)
```

Could you have a look at 2) and 4)? They seem to be fixable (while 1) and 3) are related to inactive oracles and might be expiration inconsistency). 
PS: To check if 2) would affect /v2 I have added:
```
      assert %{"expire_height" => ^expire} =
               conn |> get("/v2/oracles/#{oracle_id}") |> json_response(200)
```

**Comment by sborrazas** [comment]
@jyeshe I get 0 failures on that test module, are you sure you are up to date with syncing?

**Comment by jyeshe** [comment]
Great! Mine is 99.9929, let's see soon.

**Comment by jyeshe** [comment]
4) shouldn't fail because of:
image

**Comment by jyeshe** [comment]
It seems something with cursor, it doesn't get more 10 oracles when requests with the next cursor:
[/v2/oracles?cursor=6894-ok_R7cQfVN15F5ek1wBSYaMRjW2XbMRKx7VDQQmbtwxspjZQvmPM](http://localhost:4000/v2/oracles?cursor=6894-ok_R7cQfVN15F5ek1wBSYaMRjW2XbMRKx7VDQQmbtwxspjZQvmPM)
image

**Comment by sborrazas** [comment]
@jyeshe whatever the output of those endpoints is, integration tests should return the same output for both of us. Just to check, does `http://localhost:4000/v2/oracles/ok_zi3UaZkNWhxfR57tEE7ymNyQ2qHqtdZjQGQ7VpnmQ7MFdSL8A` return anything? if so, then test 2) shouldn't fail

**Comment by jyeshe** [comment]
> @jyeshe whatever the output of those endpoints is, integration tests should return the same output for both of us. Just to check, does `http://localhost:4000/v2/oracles/ok_zi3UaZkNWhxfR57tEE7ymNyQ2qHqtdZjQGQ7VpnmQ7MFdSL8A` return anything? if so, then test 2) shouldn't fail

Separating the cases: 
2) Is caused by sync inconsistency, the oracle is not active (doesn't exist)
4) If it returns locally more than 20 oracles on /v2, when making two requests of 10 + 10, it should work.

**Review by jyeshe — CHANGES_REQUESTED** [review]
Separating the cases:
2) Is caused by sync inconsistency, the oracle is not active (doesn't exist)
4) If it returns locally more than 20 oracles on /v2, when making two requests of 10 + 10, it should work. Not contesting your results just reporting that there is sth that might be fixed or more fault tolerant.

**Comment by sborrazas** [comment]
@jyeshe 
http://localhost:4000/v2/oracles?limit=100 returns:
58 oracles
next: null

http://localhost:4000/v2/oracles returns: 
10 oracles
next: /v2/oracles?cursor=5377806-ok_2a1CnGPKoSotzxePm12Ygz4EB2JE3C6Xz2F97evQ6NE7ENmVkp

http://localhost:4000/v2/oracles?cursor=5377806-ok_2a1CnGPKoSotzxePm12Ygz4EB2JE3C6Xz2F97evQ6NE7ENmVkp returns:
10 oracles
next: /v2/oracles?cursor=1491906-ok_a5VPJHHhiKLjRZWmuSUE9W8jSrd92T7G3F6qEEf4dC7YmGYvs

do you see anything wrong about it?

**Comment by jyeshe** [comment]
> @jyeshe http://localhost:4000/v2/oracles?limit=100 returns: 58 oracles next: null
> 
> http://localhost:4000/v2/oracles returns: 10 oracles next: /v2/oracles?cursor=5377806-ok_2a1CnGPKoSotzxePm12Ygz4EB2JE3C6Xz2F97evQ6NE7ENmVkp
> 
> http://localhost:4000/v2/oracles?cursor=5377806-ok_2a1CnGPKoSotzxePm12Ygz4EB2JE3C6Xz2F97evQ6NE7ENmVkp returns: 10 oracles next: /v2/oracles?cursor=1491906-ok_a5VPJHHhiKLjRZWmuSUE9W8jSrd92T7G3F6qEEf4dC7YmGYvs
> 
> do you see anything wrong about it?

Of course not, as I said I see only on two requests of 10 not returning 20 when one without cursor returns more than 20.

Approving since we've had oracle expirations inconsistencies that might have affected the result.

**Review by jyeshe — APPROVED** [review]

**Pull request merged**
