### PR TITLE
refactor: perform async invalidations on a sync server

### PR DESCRIPTION
**Pull request by sborrazas**
This commit contains several fixes and improvements:

* Rename the `AeMdw.Db.Sync` module to `AeMdw.Sync.Server`, since
  it contains the functionality for dealing with the syncing process.
* Merge the AeMdw.Db.ForkDetection server module into
  `AeMdw.Sync.Server`, since there was no need for it to be a separate
  process.
* Synchronously deal with syncing and invalidating, since the syncing
  process is now synchronously accepting all types of messages (which
  was probably causing issues when doing it asynchronously).
* Add documentation for how to deal with blocks when syncing.
* Allow micro-block level syncing to be more straightforward.

An important aspect as well is that everthing under the
`AeMdw.Db.Sync.*` namespace contains exclusively syncing logic,
without having to deal with processes and forks. In addition, the
syncing modules dependency is a tree-like struture: Block ->
Transaction -> *.

### CODE REVIEW

**Review by thepiwo — APPROVED** [review]
lgtm

**Review by jyeshe — COMMENTED** [review]
Checked that the invalidations are already performed synchronously because the fork detector publishes the [event](https://github.com/aeternity/ae_mdw/blob/859b452f6070f5649da11e5618a946fe5440f861/lib/ae_mdw/db/sync/fork_detector.ex#L22) and the chain subscriber only processes it after sync process [completes](https://github.com/aeternity/ae_mdw/blob/859b452f6070f5649da11e5618a946fe5440f861/lib/ae_mdw/db/sync/sync.ex#L41).

If there is no other operational issue, could we hold this PR until fully validating the RocksDB migration? Otherwise there will be conflicting changes and it will be more difficult to isolate the cause of errors.

**Comment by sborrazas** [comment]
@jyeshe I hadn't realized that because of the fact that the invalidation is done synchronously with the server process, but that  causes messages to pile up. I think it is useful to have a server that deals with messages instantly and everything else is done asynchronously, which is the right way of dealing with OTP. 

I have no problem in waiting for the rocksdb migration, but I've tested these changes and they appear to be working, even when starting/stopping the server multiple times.

**Comment by jyeshe** [comment]
Great, the PR looks good and the mdw resumed the sync after multiple restarts. My main concerns are with invalidation that is hard to test and with the isolatation of the effects of RocksDb migration.

Thanks for understanding.

**Comment by thepiwo** [comment]
should only be merged after https://github.com/aeternity/ae_mdw/pull/594

**Comment by jyeshe** [comment]
> should only be merged after #594

Which means after the validation of #594 with some full sync test, integration tests and preferably invalidation tests to assure that the outcome of the first set of changes provides a stable baseline for changing the GenServer handling forks (invalidation signals).

**Comment by jyeshe** [comment]
@sborrazas thre questions to clarify the purpose of the PR please:

1. Regarding the last bullet, `* Allow micro-block level syncing to be more straightforward`, could you help pointing out on the PR what part was changed having this goal in mind (what event is being generated or will be specifically for the micro-block syncing)?
2. The initial reason for the PR was a fix to perform invalidations **synchronously**. We've checked that it already behaves like this. Now the PR purpose is `refactor: perform async invalidations on a sync server`, in **async** way. Could you justify the change from sync to async?

**Comment by sborrazas** [comment]
> @sborrazas thre questions to clarify the purpose of the PR please:
> 
> 1. Regarding the last bullet, `* Allow micro-block level syncing to be more straightforward`, could you help pointing out on the PR what part was changed having this goal in mind (if there is an event being generated or if there will be specifically for the micro-block syncing)?

Previously the `ForkDetector` (another genserver) was doing all of the blocks subscribing and notifying the Sync server. This was not necessary and is all linearly handled by a single gen server

> 2. The initial reason for the PR was a fix to perform invalidations **synchronously**. We've checked that it already behaves like this. Now the PR purpose is `refactor: perform async invalidations on a sync server`, in **async** way. Could you justify the change from sync to async?

Invalidations were preformed synchrously on the Sync gen server process, which blocked the server from receiving any other message, potentially filling up the messages mailbox. This is not the correct way of dealing with processes with OTP applications

**Comment by jyeshe** [comment]
> > @sborrazas thre questions to clarify the purpose of the PR please:
> > 
> > 1. Regarding the last bullet, `* Allow micro-block level syncing to be more straightforward`, could you help pointing out on the PR what part was changed having this goal in mind (if there is an event being generated or if there will be specifically for the micro-block syncing)?
> 
> Previously the `ForkDetector` (another genserver) was doing all of the blocks subscribing and notifying the Sync server. This was not necessary and is all linearly handled by a single gen server
It was subscribing only to the `:top_changed` event.

> > 2. The initial reason for the PR was a fix to perform invalidations **synchronously**. We've checked that it already behaves like this. Now the PR purpose is `refactor: perform async invalidations on a sync server`, in **async** way. Could you justify the change from sync to async?
> 
> Invalidations were preformed synchrously on the Sync gen server process, which blocked the server from receiving any other message, potentially filling up the messages mailbox. This is not the correct way of dealing with processes with OTP applications
Considering the number of messages is limited, before changing it asynchronous, that makes it even harder to test, what you think about having (or could you share if already have pls) a measurement on how long does a `Sync.Invalidate.invalidate` take?

The main goal would be to avoid two changes that affect sync results so that **if** this PR could be put on hold, a virtual interference of fork handling would be isolated. This would help a lot (myself included) on the validation of results of #578.

**Comment by sborrazas** [comment]
> > > @sborrazas thre questions to clarify the purpose of the PR please:
> > > 
> > > 1. Regarding the last bullet, `* Allow micro-block level syncing to be more straightforward`, could you help pointing out on the PR what part was changed having this goal in mind (if there is an event being generated or if there will be specifically for the micro-block syncing)?
> > 
> > 
> > Previously the `ForkDetector` (another genserver) was doing all of the blocks subscribing and notifying the Sync server. This was not necessary and is all linearly handled by a single gen server
> 
> It was subscribing only to the `:top_changed` event.
> 
> > > 2. The initial reason for the PR was a fix to perform invalidations **synchronously**. We've checked that it already behaves like this. Now the PR purpose is `refactor: perform async invalidations on a sync server`, in **async** way. Could you justify the change from sync to async?
> > 
> > 
> > Invalidations were preformed synchrously on the Sync gen server process, which blocked the server from receiving any other message, potentially filling up the messages mailbox. This is not the correct way of dealing with processes with OTP applications
> 
> Considering the number of messages is limited, before changing it asynchronous, that makes it even harder to test, what you think about having (or could you share if already have pls) a measurement on how long does a `Sync.Invalidate.invalidate` take?
> 
> The main goal would be to avoid two changes that affect sync results so that **if** this PR could be put on hold, a virtual interference of fork handling would be isolated. This would help a lot (myself included) on the validation of results of #578.

Basically there were 2 processes that subscribed to two different events (ForkDetector and Sync), and whenever ForkDetector received an event it notified Sync, so why not have Sync subscribe to both instead? That's unnecessary complexity, and I'm not sure why it was done that way.

All I did on this PR is simplify many aspects of the syncing process + making sure we have an application that follows OTP standards. I have thoroughly tested this implementation with the multiple times we had to sync from scratch and I get the expected results every time.

**Review by jyeshe — APPROVED** [review]

**Pull request merged**
