### PR TITLE
feat: preload blocks when syncing

### PR DESCRIPTION
**Pull request by sborrazas**
Not sure if this is a good alternative to pre-loading chain blocks by using a buffered stream, but we could also use this stream for many other preloading opportunities throughout the code

Thoughts?

### CODE REVIEW

**Review by jyeshe — COMMENTED** [review]
I would rather use what Erlang and Elixir provides in terms of concurrency and avoid message passing without GenServer.

When the state is stored in the GenServer it's more explicit where the information is coming from and to where it's going (adheres to design by message passing). 

So in terms of design I would be in favor the #374 with the `wait` condition basically as a `GenServer.call` (avoiding custom synchronization). However, I have closed the dratf because after the 150k it became slower than master with the Node previously synced by snapshot. When the Node is busy with crypto and holding transaction locks, this might be different though.

**Comment by sborrazas** [comment]
@jyeshe as per your advice, I've just transformed the semaphore into a genserver and it looks better now (more OTP-ish). I've made two runs from 150_000 to 153_000. With the preload and a buffer size of 100, it took 839s, without the preload it took 940s, so it's a 10% gain, which I think is worth it. We can discuss this in today's meeting

**Comment by jyeshe** [comment]
> 

At the end, benchmark and tests might be used as a criteria. 

Before that, I would like to share few additional comments to detail a personal view on design based on requirements:
- generations loaded sequentially, not in parallel -> need for 1 process (favors out of the box GenServer vs multiple Tasks with max_concurrency > 1 and synchronized to avoid running in parallel)
- younger generations loaded first -> iteration needed (favors out of the box GenServer single explicit state vs stream of multiple Tasks with custom synchronization). 
- buffering -> need for a process state (favors out of the box GenServer vs custom module with custom synchronization)
- producer unbounded by consumer -> produce multiple blocks while consuming one (favors out of the box eager GenServer `:continue` vs concept of Stream which is for lazy processing)

**Comment by sborrazas** [comment]
@jyeshe I've updated the preloading as per your suggestions. Now there's a single task synchronously loading every task until the buffer fills. 

I'd like to introduce this change not only to preload blocks, but also to preload many other things that can be preloaded when syncing (I found one of them can be the microblock events which take a lot to load).

If you have any other suggested improvements, perhaps we can review these changes together, but I feel like we can all benefit from using the BufferedStream. What do you think?

**Comment by jyeshe** [comment]
I think we could put this PR and the other for parallel events (#366) on hold until we have a sync pipeline starting with the chain subscription and replacing the sync process with spawn_link decoupling the listening from loading generations and loading generations from processing them.

**Comment by jyeshe** [comment]
> @jyeshe I've updated the preloading as per your suggestions. Now there's a single task synchronously loading every task until the buffer fills.
> 
> I'd like to introduce this change not only to preload blocks, but also to preload many other things that can be preloaded when syncing (I found one of them can be the microblock events which take a lot to load).
> 
> If you have any other suggested improvements, perhaps we can review these changes together, but I feel like we can all benefit from using the BufferedStream. What do you think?

I think we could put this PR and the other for parallel events (#366) on hold until we have a sync pipeline starting with the chain subscription and replacing the sync process with spawn_link decoupling the listening from loading generations and loading generations from processing them.

**Comment by sborrazas** [comment]
Closing since @jyeshe is working on a different implementation for it

**Pull request closed without merging**
