### PR TITLE
fix: fetch key hash using aec_chain on update_aex9_presence

### PR DESCRIPTION
**Pull request by sborrazas**

### CODE REVIEW

**Review by jyeshe — APPROVED** [review]
On 1.7.2 the Mdw had all node blocks indexed before syncing. 

Makes sense for 1.9.

**Comment by jyeshe** [comment]
sth else will be needed as the error is not shown for `ct_MW1jv3erANqbwLxncgdD15GuHTQpppRpgPq51ntgE97V6Wx8G` but it was a good catch

**Comment by thepiwo** [comment]
Whats the problem that is fixing?

**Review by thepiwo — APPROVED** [review]

**Comment by sborrazas** [comment]
This is the error intended to fix
```
** (MatchError) no match of right hand side value: :not_found
    (ae_mdw 1.9.0) lib/ae_mdw/database.ex:122: AeMdw.Database.fetch!/2
    (ae_mdw 1.9.0) lib/ae_mdw/sync/async_tasks/update_aex9_presence.ex:28: anonymous fn/3 in AeMdw.Sync.AsyncTasks.UpdateAex9State.process/1
    (stdlib 3.12.1.2) timer.erl:166: :timer.tc/1
    (ae_mdw 1.9.0) lib/ae_mdw/sync/async_tasks/update_aex9_presence.ex:27: AeMdw.Sync.AsyncTasks.UpdateAex9State.process/1
    (ae_mdw 1.9.0) lib/ae_mdw/sync/async_tasks/consumer.ex:148: AeMdw.Sync.AsyncTasks.Consumer.process/1
    (ae_mdw 1.9.0) lib/ae_mdw/sync/async_tasks/consumer.ex:112: anonymous fn/2 in AeMdw.Sync.AsyncTasks.Consumer.run_supervised/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<0.103474463/0 in AeMdw.Sync.AsyncTasks.Consumer.run_supervised/2>
```

Caused by the reason @jyeshe mentioned earlier

**Pull request merged**
