### PR TITLE
test: refactor name controller integration tests

### PR DESCRIPTION
**Pull request by sborrazas**
The purpose of this is to test pagination properly, with the added
benefi that many of the tests would fail when there's name
inconsistencies in the DB.

### CODE REVIEW

**Review by jyeshe — COMMENTED** [review]
Thx, nice that it will check name consistency!
Got 3 test failures. At a glance looks like sorting:
```
  1) test names get active and inactive names, except those in auction, with default limit (Integration.AeMdwWeb.NameControllerTest)
     test/integration/ae_mdw_web/controllers/name_controller_test.exs:340
     match (=) failed
     The following variables were pinned:
       expirations = [713844, 713835, 713802, 713755, 713731, 713678, 713587, 713424, 713424, 713421]
     code:  assert ^expirations = Enum.sort(expirations)
     left:  ^expirations
     right: [713421, 713424, 713424, 713587, 713678, 713731, 713755, 713802, 713835, 713844]
     stacktrace:
       test/integration/ae_mdw_web/controllers/name_controller_test.exs:349: (test)

.....

  2) test names get active and inactive names, except those in auction, with limit=2 (Integration.AeMdwWeb.NameControllerTest)
     test/integration/ae_mdw_web/controllers/name_controller_test.exs:363
     match (=) failed
     The following variables were pinned:
       expirations = [713844, 713835]
     code:  assert ^expirations = Enum.sort(expirations)
     left:  ^expirations
     right: [713835, 713844]
     stacktrace:
       test/integration/ae_mdw_web/controllers/name_controller_test.exs:371: (test)

..............

  3) test inactive_names get inactive names forward with limit=6 (Integration.AeMdwWeb.NameControllerTest)
     test/integration/ae_mdw_web/controllers/name_controller_test.exs:169
     match (=) failed
     The following variables were pinned:
       next_expirations = [84923, 40195, 40537, 67160]
     code:  assert ^next_expirations = Enum.sort(next_expirations)
     left:  ^next_expirations
     right: [40195, 40537, 67160, 84923]
     stacktrace:
       test/integration/ae_mdw_web/controllers/name_controller_test.exs:191: (test)

.....

Finished in 1.5 seconds
36 tests, 3 failures
```

**Comment by sborrazas** [comment]
@jyeshe I had those same failures as well, but if you look into it, you'll find that those are caused by the inconsistent DB state. You can check if your DB is inconsistent by running the following:
```elixir
alias AeMdw.Db.Model
alias AeMdw.Mnesia
require Model

table_active = Model.ActiveName
table_active_expiration = Model.ActiveNameExpiration

:mnesia.dirty_all_keys(table_active_expiration) |> Enum.map(fn {exp, plain} -> case Mnesia.fetch(table_active, plain) do {:ok, Model.name(expire: expire)} -> {exp, plain, expire}; _blah -> {exp, plain, :not_found} end; end) |> Enum.filter(fn {exp1, plain, exp2} -> exp1 != exp2 end)
```

If you get any results back, it means the DB is in an inconsistent state, and there exist names that have a different expiration on the `ActiveName` table (the table used to display the names data) and the `ActiveNameExpiration` table (the table used to retrieve the names sorted by expiration).

**Comment by sborrazas** [comment]
@jyeshe I just realized two of them were because of an error. But the third one still happens because of the inconsistent DB state.

**Comment by jyeshe** [comment]
> @jyeshe I just realized two of them were because of an error. But the third one still happens because of the inconsistent DB state.

Here only 1 now too. It seems there is something very tricky happening to this first entry of the `next`:
```
iex(aeternity@localhost)2> :mnesia.dirty_all_keys(Model.InactiveNameExpiration) |> Enum.group_by(fn {_height, name} -> name end) |> Enum.filter(fn {name, _expirations} -> name == "pppkkk.test" end) 
[{"pppkkk.test", [{34923, "pppkkk.test"}]}]
iex(aeternity@localhost)3> :mnesia.dirty_all_keys(Model.ActiveNameExpiration) |> Enum.group_by(fn {_height, name} -> name end) |> Enum.filter(fn {name, _expirations} -> name == "pppkkk.test" end)  
[]
```

**Review by jyeshe — APPROVED** [review]
The last one that fails is due to db state:
```
iex(aeternity@localhost)1> :mnesia.dirty_all_keys(Model.InactiveNameExpiration) |> Enum.filter(fn {_exp, name} -> name == "pppkkk.test" end)                                                                                                                                   [{34923, "pppkkk.test"}]
```
while the expiration is:
```
iex(aeternity@localhost)2> :mnesia.dirty_read(Model.InactiveName, "pppkkk.test")                                                        [
{:name, "pppkkk.test", 34923, 84923, [{{34923, 0}, 602471}],
[{{34923, 1}, 602472}], [], {{34923, 2}, 602473}, 0,
<<140, 45, 15, 171, 198, 112, 76, 122, 188, 218, 79, 0, 14, 175, 238, 64, 9,
82, 93, 44, 169, 176, 237, 27, 115, 221, 101, 211, 5, 168, 169, 235>>, nil}
]
```

**Review by thepiwo — APPROVED** [review]

**Pull request merged**
