### PR TITLE
feat: include source tx_hash on nested names endpoints

### PR DESCRIPTION
**Pull request by sborrazas**

### CODE REVIEW

**Review by jyeshe — COMMENTED** [review]
The tx hash seems helpful, the tx type is already returned under `tx`:
image

**Comment by sborrazas** [comment]
> The tx hash seems helpful, the tx type is already returned under `tx`: image

The `tx_type` does not always match the `tx_type` from the tx object. for instance, with name claims `tx_type` can either be `NameClaimTx` or `ContractCallTx`

**Comment by jyeshe** [comment]
> > The tx hash seems helpful, the tx type is already returned under `tx`: image
> 
> The `tx_type` does not always match the `tx_type` from the tx object. for instance, with name claims `tx_type` can either be `NameClaimTx` or `ContractCallTx`

I see the `tx` is not actual chain transaction, might be an internal one. Having `tx_type` and `tx.type` that might differ it's a bit confusing to me. If not for a specific reason, indicating if it's from a contract call or not with a boolean might to be more clear.

**Review by jyeshe — COMMENTED** [review]
I see, might be an internal tx not the chain one. Having tx_type and tx.type that might differ it's a bit confusing to me. If not for a specific reason, indicating if it's from a contract call or not with a boolean might to be more clear.

**Comment by sborrazas** [comment]
> I see, might be an internal tx not the chain one. Having tx_type and tx.type that might differ it's a bit confusing to me. If not for a specific reason, indicating if it's from a contract call or not with a boolean might to be more clear.

Renamed the field to `source_tx_hash` and `source_tx_type`. Also added boolean `internal_source` to indicate whether it's internal or not

**Pull request merged**
